### PR TITLE
needs-rebase update owners

### PR DESCRIPTION
**Pull request by harixminds**

### CODE REVIEW

**Comment by zhanghe9702** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/zhanghe9702/readygo/pull/12#" title="Author self-approved">harixminds</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **zhanghe-prow-bot**
You can assign the PR to them by writing `/assign @zhanghe-prow-bot` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=zhanghe9702%2Freadygo).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/zhanghe9702/readygo/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by zhanghe9702** [comment]
Welcome @harixminds! <br><br>It looks like this is your first PR to <a href='https://github.com/zhanghe9702/readygo'>zhanghe9702/readygo</a> 🎉.  :smiley:

**Comment by zhanghe9702** [comment]
Hi @harixminds. Thanks for your PR.

I'm waiting for a [zhanghe9702](https://github.com/orgs/zhanghe9702/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://git.k8s.io/community/community-membership.md#member) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=zhanghe9702%2Freadygo).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by harixminds** [comment]
adorees code ok?

**Review by zhanghe9702 — APPROVED** [review]
/lgtm

**Comment by zhanghe9702** [comment]
@harixminds: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pull-readygo-go-build | 4800225b53126bb5fc3356ffaaec89efc7e78000 | [link](https://prow.cloudminds.com:31008/view/s3/prow-logs/pr-logs/pull/zhanghe9702_readygo/12/pull-readygo-go-build/1310842766074318848) | `/test pull-readygo-go-build`

[Full PR test history](https://prow.cloudminds.com:31008/pr-history?org=zhanghe9702&repo=readygo&pr=12)

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by zhanghe9702** [comment]
@harixminds: Cannot trigger testing until a trusted user reviews the PR and leaves an `/ok-to-test` message.

<details>

In response to [this](https://github.com/zhanghe9702/readygo/pull/12#issuecomment-700618487):

>/retest


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by zhanghe9702** [comment]
@harixminds: Cannot trigger testing until a trusted user reviews the PR and leaves an `/ok-to-test` message.

<details>

In response to [this](https://github.com/zhanghe9702/readygo/pull/12#issuecomment-700630662):

>/retest


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by zhanghe9702** [comment]
@harixminds: Cannot trigger testing until a trusted user reviews the PR and leaves an `/ok-to-test` message.

<details>

In response to [this](https://github.com/zhanghe9702/readygo/pull/12#issuecomment-700632660):

>/retest


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by zhanghe9702** [comment]
@harixminds: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pull-readygo-go-build | 4800225b53126bb5fc3356ffaaec89efc7e78000 | [link](https://prow.cloudminds.com:31008/view/file/prow-logs/pr-logs/pull/zhanghe9702_readygo/12/pull-readygo-go-build/1310901506060324864) | `/test pull-readygo-go-build`

[Full PR test history](https://prow.cloudminds.com:31008/pr-history?org=zhanghe9702&repo=readygo&pr=12)

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
